# Generated by Django 3.0.3 on 2022-04-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_idempotency_key', '0002_alter_idempotencykey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idempotencykey',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='idempotencykey',
            name='Unique IdempotencyKey (user, idempotency_key)',
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(
                fields=('idempotency_key',), name='Unique IdempotencyKey (idempotency_key)'
            ),
        ),
    ]
